# We need this docker-compose.yml file because AWS Elastic Beanstalk looks for it by default
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'