version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # use node_modules that already exists inside the container; don't mount node_modules sinc it won't exist on host
      - .:/app # mount everything in current directory to /app
  
  # We need a separate service so changes in test files are detected live (adding a test and saving it will trigger a test run)
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]